@startuml

|#lightblue|人事主管|
start
repeat :员工入职手续填写;

if (选择提交) then (中心主任)
    |#lightgray|中心主任|
    :审批;
endif

|#lightblue|人事主管|
backward:重新填写;
repeat while (通过？) is (否) not (是)
repeat :员工信息管理;
stop
@enduml