@startuml

skinparam defaultFontName STFangsong

|#lightblue|员工|
start
repeat :差旅报备填写;

if (选择提交) then (部门领导)
    |#lightgray|部门领导|
    :审批;
else (团队领导)
    |#LightGreen|团队领导|
    :审批;
endif

|#lightblue|员工|
backward:重填报备;
repeat while (通过？) is (否) not (是)

stop
@enduml