@startuml

|#lightblue|人事主管|
start
repeat :维护应聘人员信息;

:关联用人需求;
|#lightgray|需求部门|
if (确认是否面试) then (是)
    |#lightgray|人事主管|
    :通知面试;
else (否)
    |#lightgray|人事主管|
    :纳入人才库;
    end
endif

|#lightblue|需求部门|
repeat :确认面试结果;
if (是否通过面试？) then (否) 
    |#lightgray|人事主管|
    :纳入人才库;
    end
else  (是) 
   |#lightgray|人事主管|
    :员工入职管理; 


stop
@enduml
